version: '3'

services:
  nodeapp:
    build:
      context: app
    container_name: nodeapp
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh
    command: npm start
    volumes:
      - ./app:/usr/app
      - /usr/app/node_modules
    ports:
      - '3000:3000'
    networks:
      - fullstack
    tty: true
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root 
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
    
  